"""Model registry. Importing this module registers every table on ``Base.metadata``."""

from app.db.base import Base
from app.models.campaigns import (
    Advertisement,
    Campaign,
    CampaignDailySpend,
    CampaignPublisher,
    CampaignTarget,
)
from app.models.delivery import AdDelivery, Click, ConversionEvent, Impression
from app.models.identity import Advertiser, Publisher, StaffUser, User
from app.models.money import (
    DailyFinancialSnapshot,
    Deposit,
    LedgerAccount,
    LedgerEntry,
    LedgerTransaction,
    PayoutMethodRecord,
    PublisherEarning,
    Refund,
    Wallet,
    WalletTransaction,
    Withdrawal,
)
from app.models.ops import (
    AuditLog,
    Category,
    EventLog,
    FraudCase,
    FraudEvent,
    FraudScore,
    IdempotencyRecord,
    ModerationReview,
    Notification,
    PricingRule,
    Report,
    SystemSetting,
)
from app.models.telegram import (
    ChannelStatDaily,
    ChannelVerificationAttempt,
    PublisherChannel,
    TelegramChat,
)

__all__ = [
    "Base",
    "AdDelivery",
    "Advertisement",
    "Advertiser",
    "AuditLog",
    "Campaign",
    "CampaignDailySpend",
    "CampaignPublisher",
    "CampaignTarget",
    "Category",
    "ChannelStatDaily",
    "ChannelVerificationAttempt",
    "Click",
    "ConversionEvent",
    "DailyFinancialSnapshot",
    "Deposit",
    "EventLog",
    "FraudCase",
    "FraudEvent",
    "FraudScore",
    "IdempotencyRecord",
    "Impression",
    "LedgerAccount",
    "LedgerEntry",
    "LedgerTransaction",
    "ModerationReview",
    "Notification",
    "PayoutMethodRecord",
    "PricingRule",
    "Publisher",
    "PublisherChannel",
    "PublisherEarning",
    "Refund",
    "Report",
    "StaffUser",
    "SystemSetting",
    "TelegramChat",
    "User",
    "Wallet",
    "WalletTransaction",
    "Withdrawal",
]
